export {
  api,
  authApi,
  miembrosApi,
  usuariosApi,
  unidadesApi,
  rbacApi,
  administrativoApi,
  adultosApi,
  fichaMedicaApi,
  catalogoApi,
  progresionApi,
  organizacionApi,
  descargarArchivo,
} from './endpoints';
